repository:
  name: elasticsearch-logstash-kibana
  description: ELK and FastAPI
  topics: elasticsearch, logstash, kibana, python, fastapi, docker
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

teams:
  - name: olahsymbo
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        require_code_owner_reviews: true